apiVersion: apps/v1

kind: Deployment

metadata:

  name: todoapp-deployment

  labels:

    app: todo-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todo-app

  template:

    metadata:

      labels:

        app: todo-app

    spec:

      containers:

      - name: todo-app

        image: blackzu69/todo-app

        ports:

        - containerPort: 8000

